write_space/accounts/urls.py
from django.contrib.auth import views as auth_views
from django.urls import path
from . import views
from accounts.forms import LoginForm

app_name="accounts"

urlpatterns=[
path("login/",auth_views.LoginView.as_view(authentication_form=LoginForm,template_name="accounts/login.html"),name="login"),
path("logout/",auth_views.LogoutView.as_view(),name="logout"),
path("signup/",views.signup,name="signup"),
path("first_step/",views.selectinterest,name="select_interest"),
path("second_step/",views.selectprofilepicture,name="select_pic"),
path("user_profile/<str:username>/<int:pk>/",views.profileView.as_view(),name="user_profile"),
path("user_profile/change_pic/<str:username>/<int:pk>/",views.change_profile_pic_view,name="change_pic"),
path("follow/<str:username>/<int:pk>/",views.follow_view,name="follow"),
path("unfollow/<str:username>/<int:pk>/",views.unfollow_view,name="unfollow"),
path("<str:username>/<int:pk>/following",views.Following.as_view(),name="following"),
path("<str:username>/<int:pk>/Bio",views.Bio.as_view(),name="bio"),
path("interests/<str:username>/<int:pk>/",views.interestView.as_view(),name="interests"),
]

write_space/posts/urls.py
from django.urls import path
from . import views
from .feeds import LatestPostsFeed

app_name = "posts"

urlpatterns = [

 path("<str:username>/post/all/",views.userPostListView.as_view(),name="user_post_list"),
 path('<str:username>/post/<int:pk>/',views.userPostDetailView.as_view(),name="user_post_detail"),
 path("<int:pk>/unsave/",views.postUnsaveView.as_view(),name="unsave"),
 path('<int:pk>/save_for_future/',views.postSaveView.as_view(),name="save_for_future"),
 path("all/",views.postListView.as_view(),name="post_list"),
 path('<int:pk>/',views.PostDetailView.as_view(),name="post_detail"),
 path("<str:username>/new/",views.CreatePostView.as_view(),name="create_post"),
 path('<int:pk>/edit/',views.PostUpdateView.as_view(),name="edit_post"),
 path('<str:username>/<int:pk>/delete/',views.PostDeleteView.as_view(),name="delete_post"),
 path("<str:username>/saved/",views.savedListView.as_view(),name="view_saved"),
 path('<int:pk>/comment/',views.add_comment_to_post,name="add_comment_to_post"),
 path('<int:pk>/clap/',views.postClapView.as_view(),name="clap"),
 path('<int:pk>/un_clap/',views.postUnClapView.as_view(),name="un_clap"),
 path('cartegory/<str:name>/',views.cartegoryView.as_view(),name="cartegory"),
 path('<int:pk>/publish/',views.post_publish,name="post_publish"),
 path('<int:pk>/unpublish/',views.post_unpublish,name="post_unpublish"),
 path('join_cartegory/<int:pk>/',views.join_cartegory_view,name="join_cartegory"),
 path('leave_cartegory/<int:pk>/',views.leave_cartegory_view,name="leave_cartegory"),
 path("feed/rss", LatestPostsFeed(), name="post_feed"),
]

write_space/write_space/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static
from rest_framework_jwt.views import obtain_jwt_token,refresh_jwt_token
from . import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path("", views.LandingPage.as_view(),name="landing_page"),
    path("posts/",include("posts.urls",namespace="posts")),
    path("api/posts/",include("posts.api.urls",namespace="posts_api")),
    path("accounts/",include("accounts.urls",namespace="accounts")),
    path("api/token-auth/", obtain_jwt_token),
    path("api/refresh_token/",refresh_jwt_token),
    path("api/accounts/",include("accounts.api.urls",namespace="accounts_api")),
    path("api/images/<int:pk>/<str:username>/<str:folder>/<str:public_id>/<str:type>/delete",
    views.delete_image_async,name="delete_image_async"),
    path("accounts/",include("django.contrib.auth.urls")),
    path("about_me/",views.aboutView.as_view(),name="about_me"),
    path('summernote/', include('django_summernote.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

write_space/templates/about.html
{%extends "header_footer.html"%}
{%load staticfiles%}


{%block content%}


<br>
<br>
<div class="jumbotron jumbotron-fluid" id="first_jumbo1">
  <div class="container text-center ">
    <h2>About This Project</h2>

    <!-- <h3>This pa</h3> -->
  </div>
  </div>
  <div class="container">
    <h3>This is an open-source blog project built on Django</h3>
    <h4>If you would love to make a suggestion or a pull request, visit <a href="https://github.com/NdibeRaymond/Write_space"><i class="fa fa-github 2x"></i></a> to get started</h4>

  </div>
<div class="jumbotron jumbotron-fluid" id="first_jumbo1">
  <div class="container text-center ">
    <h2>About Raymond</h2>

  </div>
  </div>


<div class="container">
  <img src="{% static 'write_space/images/Raymond.png' %}" alt="" id="profile_pic" style="margin: 0 auto;display:block">
  <h4>I am Raymond, Outreachy intern 2020, a Full-stack Web Developer focusing on Frontend, a Chatbot Develper and a Google Cloud Engineer<br>
  This project was built and is being maintained by me as an open-source multi-user blogging project. we accept all kinds of contributions and would be very happy if you can consider contributing.<br>
  Since you are here, it would be great if you
go through the site, check things out and drop you feedback on what looks right and what doesn't.<br>
You can reach me on the links below</h4>




  <div class="text-center" >
    <a href="#" class="about_anchor"><i class="fa fa-twitter"></i></a>
    <a href="https://linkedin.com/in/raymond-olisaemeka-3a67b9160" class="about_anchor"><i class="fa fa-linkedin"></i></a>
    <a href="https://github.com/NdibeRaymond" class="about_anchor"><i class="fa fa-github"></i></a>
  </div>

</div>

<br>
<br>
<br>
{%endblock%}

write_space/templates/base.html
<!DOCTYPE html>
{%load staticfiles%}
<html lang="en" dir="ltr">
<head>
  <!-- Global site tag (gtag.js) - Google Analytics -->
  <script async src="https://www.googletagmanager.com/gtag/js?id=UA-140043490-1"></script>
  <script>
    window.dataLayer = window.dataLayer || [];
    function gtag(){dataLayer.push(arguments);}
    gtag('js', new Date());

    gtag('config', 'UA-140043490-1');
  </script>

  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'write_space/css/master.css' %}">
    <link href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet" integrity="sha384-wvfXpqpZZVQGK6TAh5PVlGOfQNHSoD2xbE+QkPxCAFlNEevoEH3Sl0sibVcOQVnN" crossorigin="anonymous">
    <link href="https://cdnjs.cloudflare.com/ajax/libs/summernote/0.8.11/summernote.css" rel="stylesheet">
    <link href="{% static 'write_space/css/summernote_plugin.css' %}" rel="stylesheet">

<!-- <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css"> -->
<style>
.post_body_image {
  width: 70%;
  height:auto;
}
</style>


  <title></title>
</head>
  <body>
    <i id="user_identity" username="{{request.user.username}}" pk="{{request.user.pk}}"></i>
    {% block body_block %}
    {%endblock%}

    <script src="http://code.jquery.com/jquery-3.1.1.js" integrity="sha256-16cdPddA6VdVInumRGo6IbivbERE8p7CQR3HzTBuELA=" crossorigin="anonymous"></script>  <!-- Latest compiled and minified JavaScript -->
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/sharer.js@latest/sharer.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/summernote/0.8.11/summernote.min.js"></script>
    <script src="https://widget.cloudinary.com/v2.0/global/all.js" type="text/javascript"></script>
    <script src="{% static 'write_space/js/summernote_plugin.js' %}"></script>
    <script src="{% static 'write_space/js/transparent_to_solid_navbar.js' %}"></script>
    <script src="{% static 'write_space/js/back_to_top.js' %}"></script>
    <script src="{% static 'write_space/js/main.js' %}"></script>



  </body>
</html>

write_space/templates/header_footer.html
{% extends "base.html" %}
{% load staticfiles %}
{% block body_block %}
<header>
  {% if user.is_authenticated %}
  <!-- this is the big navbar. displayed when the screen is large -->

<!-- this is the small navbar. its displayed when the screen is small -->
  <nav class="navbar navbar-default navbar-fixed-top full_opacity" id="nav">
      <!-- Brand and toggle get grouped for better mobile display -->
          <div class="">
            <a class="navbar-brand head" href="/" id="head1">WriteSpace</a>
          </div>

        <div class="flex-nav-right">
        <div class="">
            <a class="navbar-brand head" href="{%url 'posts:user_post_list' username=user.username %}" id="head1">Posts</a>
        </div>

        <div class="">
            <a class="navbar-brand head" href="{%url 'accounts:following' username=request.user.username pk=request.user.pk %}" id="head1">Following</a>
        </div>
        {%if request.user.userprofile.profile_pic%}
          <a href="#" id="no_border_bottom" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false"><img src="{{request.user.userprofile.profile_pic}}" alt="avatar" class="avatar"></a>
        {%else%}
        {%if request.user.userprofile.gender == 'F' %}
          <a href="#" id="no_border_bottom" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false"><img src="{%static 'write_space/images/Capture8 copy.png'%}" alt="avatar" class="avatar"></a>
        {%elif request.user.userprofile.gender == 'M' %}
          <a href="#" id="no_border_bottom" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false"><img src="{%static 'write_space/images/Capture7 copy.png'%}" alt="avatar" class="avatar"></a>
        {%else%}
          <a href="#" id="no_border_bottom" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false"><img src="{%static 'write_space/images/neutral.png'%}" alt="avatar" class="avatar"></a>
        {%endif%}
        {%endif%}
        <ul class="dropdown-menu">
          <li><p class="profile_name">{{request.user.username}}</p></li>
          <hr>
          <li><a id="profile" href="{%url 'accounts:user_profile' username=request.user.username pk=request.user.pk %}">Profile</a></li>
          <li><a id="profile" href="{%url 'posts:user_post_list' username=user.username %}">Posts</a></li>
          <li><a id="profile" href="{% url 'posts:view_saved' username=request.user.username %}">Saved</a></li>
          <li role="separator" class="divider"></li>
          <li><a href="{%url 'about_me'%}">About me</a></li>
          <li><a id="profile" href="{% url 'accounts:logout' %}">Logout</a></li>
        </ul>
      </div>
  </nav>
  {%else%}
  <!-- this navbar is displayed if the user is not logged in -->
  <nav class="navbar navbar-default navbar-fixed-top top_nav">
    <div class="container-fluid">
      <!-- Brand and toggle get grouped for better mobile display -->
      <div class="navbar-header">
        <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar head"></span>
          <span class="icon-bar head"></span>
          <span class="icon-bar head"></span>
        </button>
        <a class="navbar-brand head" id = "brand" href="/">WriteSpace</a>
      </div>

      <!-- Collect the nav links, forms, and other content for toggling -->
      <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
        <ul class="nav navbar-nav">
        </ul>

        <ul  class="nav navbar-nav navbar-right">
            <li><a href="{%url 'about_me'%}">About</a></li>
          <li><a href="{% url 'accounts:signup' %}">Signup</a></li>
          <li><a href="{% url 'accounts:login' %}" id= "login">Login</a></li>


        </ul>
      </div><!-- /.navbar-collapse -->
    </div><!-- /.container-fluid -->
  </nav>
  {%endif%}
</header>

<nav class="navbar navbar-default sticky">
   <ul class="nav navbar-nav" id="profile_nav">
     <!-- <li class="tabs__tab">
       <a id="home" href="/" class="current">
         <span class="links__text">Explore</span>
       </a>
     </li> -->
     <li class="tabs__tab">
       <a id="deal_hub" href="{%url 'posts:cartegory' name='Tech' %}" class="">
         <span class="links__text">Tech</span>
       </a>
     </li>
     <li class="" id = "Poll2_1">
       <a id="talks" name="" href="{%url 'posts:cartegory' name='Business' %}">
         <span class="">Business</span>
       </a>
     </li>
     <li class="tabs__tab">
       <a id="nominations" name="" href="{%url 'posts:cartegory' name='Relationship' %}" class="">
         <span class="links__text">Relationship</span>
       </a>
     </li>
     <li class="tabs__tab">
       <a id="nominations" name="" href="{%url 'posts:cartegory' name='Art' %}" class="">
         <span class="links__text">Art</span>
       </a>
     </li>
   <li class="tabs__tab" id="Poll2_2">
     <a id="nominations" name="" href="{%url 'posts:cartegory' name='Sports' %}" class="">
       <span class="links__text">Sports</span>
     </a>
   </li>
   <li class="tabs__tab" id="Poll1_1">
     <a id="nominations" name="Polls" href="{%url 'posts:cartegory' name='Education' %}" class="">
       <span class="links__text">Education</span>
     </a>
   </li>
   <li class="" id = "Poll1_2">
     <a id="nominations" name="" href="{%url 'posts:cartegory' name='Politics' %}" class="">
       <span class="">Politics</span>
     </a>
   </li>
   <li class="tabs__tab" id="Poll3_2">
     <a id="nominations" name="" href="{%url 'posts:cartegory' name='Sexuality' %}" class="">
       <span class="links__text">Sexuality</span>
     </a>
   </li>

   <li class="" id="Poll3_1">
     <a id="nominations" name="" href="{%url 'posts:cartegory' name='Science' %}" class="">
       <span class="">Science</span>
     </a>
   </li>
   <li class="" id= "Poll1_3">
     <a id="nominations" name="" href="{%url 'posts:cartegory' name='Religion' %}" class="">
       <span class="">Religion</span>
     </a>
   </li>
   <li class="tabs__tab">
     <a id="nominations" name="" href="{%url 'posts:cartegory' name='All' %}" class="">
       <span class="links__text">More</span><span>&nbsp;>></span>
     </a>
   </li>
   </ul>
 </nav>

<div id="root">
{%block content%}
{%endblock%}
</div>
    <footer>
      <div class="container">
        <div class="row" id="first_footer">
          <div class="col-lg-3 col-md-3 col-sm-6 col-xs-6">
            <br>
            <a href="{%url 'about_me'%}""><h4 >Meet Raymond!</h4></a>
          </div>
          <div class="col-lg-3 col-md-3 col-sm-6 col-xs-6">
            <div>
              <ul>
                <li class="dropdown">
                  <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false"><h4>Contact <span class="caret"></span></h4></a>
                  <ul class="dropdown-menu">
                    <li><a href="#">+2349035234033</a></li>
                    <li role="separator" class="divider"></li>
                    <li><a href="#">+23409096222696</a></li>


                  </ul>
                </li>
              </ul>
            </div>
          </div>
          <div class="col-lg-3 col-md-3 col-sm-6 col-xs-6">
            <br>
            <a href="#" ><h4>Help center</h4></a>
          </div>

          <div class="col-lg-3 col-md-3 col-sm-6 col-xs-6">
            <br>
            <a href="#" ><h4>Privacy Policy</h4></a>
          </div>
        </div>
      </div>
      <hr id="footer_divider">
      <div id="second_footer">

        <div>

          <a style="display:inherit;justify-content:center" href="https://web.facebook.com/NdibeRaymond"><i class="fa fa-facebook fa-2x" style="color:white" aria-hidden="true"></i></a>

          <a href="https://twitter.com/CodeBlooded_JS"><i class="fa fa-twitter fa-2x" style="color:white" aria-hidden="true"></i></a>

          <a href="https://github.com/NdibeRaymond"><i class="fa fa-github-alt fa-2x" style="color:white" aria-hidden="true"></i></a>

          <a href="https://www.linkedin.com/in/raymond-ndibe-3a67b9160/"><i class="fa fa-linkedin fa-2x" style="color:white" aria-hidden="true"></i></a>

        </div>
    </footer>
    <footer
    id="all_rights_reserved"><h5>© 2020 WriteSpace All rights reserved.</h5>
  </footer>

    <!-- <a href="#" class="back-to-top"><img src="arrow-in-circle-point-to-up.png" alt=""></a> -->
    <!-- <script src="http://code.jquery.com/jquery-3.1.1.js" integrity="sha256-16cdPddA6VdVInumRGo6IbivbERE8p7CQR3HzTBuELA=" crossorigin="anonymous"></script>  <!-- Latest compiled and minified JavaScript --> -->
    <!-- <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script> -->

{%endblock%}