write_space/accounts/api/urls.py
from django.urls import path
from . import views

app_name = "accounts_api"

urlpatterns = [
    path("signup/",views.userCreateApiView.as_view(),name="signup"),
    path("login/",views.userLoginApiView.as_view(),name="login"),
]

write_space/accounts/urls.py
from django.contrib.auth import views as auth_views
from django.urls import path
from . import views
from accounts.forms import LoginForm

app_name="accounts"

urlpatterns=[
path("login/",auth_views.LoginView.as_view(authentication_form=LoginForm,template_name="accounts/login.html"),name="login"),
path("logout/",auth_views.LogoutView.as_view(),name="logout"),
path("signup/",views.signup,name="signup"),
path("first_step/",views.selectinterest,name="select_interest"),
path("second_step/",views.selectprofilepicture,name="select_pic"),
path("user_profile/<str:username>/<int:pk>/",views.profileView.as_view(),name="user_profile"),
path("user_profile/change_pic/<str:username>/<int:pk>/",views.change_profile_pic_view,name="change_pic"),
path("follow/<str:username>/<int:pk>/",views.follow_view,name="follow"),
path("unfollow/<str:username>/<int:pk>/",views.unfollow_view,name="unfollow"),
path("<str:username>/<int:pk>/following",views.Following.as_view(),name="following"),
path("<str:username>/<int:pk>/Bio",views.Bio.as_view(),name="bio"),
path("interests/<str:username>/<int:pk>/",views.interestView.as_view(),name="interests"),
]

write_space/posts/urls.py
from django.urls import path
from . import views
from .feeds import LatestPostsFeed

app_name = "posts"

urlpatterns = [

 path("<str:username>/post/all/",views.userPostListView.as_view(),name="user_post_list"),
 path('<str:username>/post/<int:pk>/',views.userPostDetailView.as_view(),name="user_post_detail"),
 path("<int:pk>/unsave/",views.postUnsaveView.as_view(),name="unsave"),
 path('<int:pk>/save_for_future/',views.postSaveView.as_view(),name="save_for_future"),
 path("all/",views.postListView.as_view(),name="post_list"),
 path('<int:pk>/',views.PostDetailView.as_view(),name="post_detail"),
 path("<str:username>/new/",views.CreatePostView.as_view(),name="create_post"),
 path('<int:pk>/edit/',views.PostUpdateView.as_view(),name="edit_post"),
 path('<str:username>/<int:pk>/delete/',views.PostDeleteView.as_view(),name="delete_post"),
 path("<str:username>/saved/",views.savedListView.as_view(),name="view_saved"),
 path('<int:pk>/comment/',views.add_comment_to_post,name="add_comment_to_post"),
 path('<int:pk>/clap/',views.postClapView.as_view(),name="clap"),
 path('<int:pk>/un_clap/',views.postUnClapView.as_view(),name="un_clap"),
 path('cartegory/<str:name>/',views.cartegoryView.as_view(),name="cartegory"),
 path('<int:pk>/publish/',views.post_publish,name="post_publish"),
 path('<int:pk>/unpublish/',views.post_unpublish,name="post_unpublish"),
 path('join_cartegory/<int:pk>/',views.join_cartegory_view,name="join_cartegory"),
 path('leave_cartegory/<int:pk>/',views.leave_cartegory_view,name="leave_cartegory"),
 path("feed/rss", LatestPostsFeed(), name="post_feed"),
]

write_space/write_space/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static
from rest_framework_jwt.views import obtain_jwt_token,refresh_jwt_token
from . import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path("", views.LandingPage.as_view(),name="landing_page"),
    path("posts/",include("posts.urls",namespace="posts")),
    path("api/posts/",include("posts.api.urls",namespace="posts_api")),
    path("accounts/",include("accounts.urls",namespace="accounts")),
    path("api/token-auth/", obtain_jwt_token),
    path("api/refresh_token/",refresh_jwt_token),
    path("api/accounts/",include("accounts.api.urls",namespace="accounts_api")),
    path("api/images/<int:pk>/<str:username>/<str:folder>/<str:public_id>/<str:type>/delete",
    views.delete_image_async,name="delete_image_async"),
    path("accounts/",include("django.contrib.auth.urls")),
    path("about_me/",views.aboutView.as_view(),name="about_me"),
    path('summernote/', include('django_summernote.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

write_space/accounts/models.py
from django.db import models
from django.contrib.auth.models import User
from posts.models import Cartegory
from posts.models import Post
from django.urls import reverse

# Create your models here.
class userProfile(models.Model):
    user = models.OneToOneField(User,on_delete = models.CASCADE)

    #additional

    bio = models.CharField(max_length = 1000,blank = True)
    profile_pic = models.URLField(blank=True,null=True)
    background_pic = models.URLField(blank=True,null=True)
    date_joined = models.DateTimeField(auto_now=True)
    follower = models.ManyToManyField("self",symmetrical=False)
    saved_for_future = models.ManyToManyField(Post,blank=True,related_name="saved")
    gender = models.CharField(max_length = 5,blank=False,default="")
    interests = models.ManyToManyField(Cartegory,blank=True)

    def __str__(self):
        return "@{}".format(self.user.username)


    def get_absolute_url(self):
        return reverse("accounts:user_profile",kwargs={"pk":self.pk,"username":self.user.username})

    def get_success_url(self):
        return HttpResponseRedirect(reverse_lazy(self.request.META.get('HTTP_REFERER')))

write_space/accounts/api/views.py
from rest_framework.generics import (ListAPIView,RetrieveAPIView
,RetrieveUpdateAPIView,RetrieveDestroyAPIView,CreateAPIView)

from rest_framework.response import Response
from rest_framework.status import HTTP_200_OK, HTTP_400_BAD_REQUEST
from rest_framework.views import APIView

from rest_framework.permissions import (AllowAny,IsAuthenticated,IsAdminUser
,IsAuthenticatedOrReadOnly)
from rest_framework.filters import SearchFilter,OrderingFilter
from rest_framework.mixins import DestroyModelMixin, UpdateModelMixin
# from .permissions import IsOwnerOrReadOnly

from django.contrib.auth import get_user_model
User = get_user_model()

from . import serializers

# from .pagination import postLimitOffsetPagination,postPageNumberPagination


class userCreateApiView(CreateAPIView):
    serializer_class = serializers.userCreateSerializer
    queryset = User.objects.all()


class userLoginApiView(APIView):
    serializer_class = serializers.userLoginSerializer
    permission_classes = [AllowAny]

    def post(self,request,*args,**kwargs):
        data = request.data
        serializer = serializers.userLoginSerializer(data=data)
        if serializer.is_valid(raise_exception=True):
            new_data = serializer.data
            return Response(new_data,status=HTTP_200_OK)
        return Response(serializer.errors,status=HTTP_400_BAD_REQUEST)

write_space/accounts/views.py
from django.shortcuts import render,redirect
from django.urls import reverse,reverse_lazy
from . import forms
from django.views import generic
from accounts import models
from posts.models import Cartegory,Post
from django.http import HttpResponseRedirect
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.decorators import login_required
from django.contrib.auth import get_user_model
from django.views.generic import CreateView
import json


# Create your views here.


#########################################################
## used to implement the profile viewing functionality
######################################################
class profileView(LoginRequiredMixin,generic.TemplateView):
    login_url="/accounts/login/"
    template_name="accounts/user_profile.html"
    model=Post

    def get_context_data(self,**kwargs):
        all_posts = Post.objects.all()
        userprofiles=models.userProfile.objects.all()
        user = get_user_model().objects.get(username=self.kwargs.get("username"))
        try:
            user_posts = all_posts.filter(author=user)
        except:
            user_posts = []
        try:
            user_comments = all_posts.filter(comments__author=user)
        except:
            user_comments = []
        try:
            posts_viewed = all_posts.filter(viewed=user)
        except:
            posts_viewed = []
        try:
            following=userprofiles.filter(follower=user.userprofile)
        except:
            following = []
        context = super(profileView,self).get_context_data(**kwargs)
        context["user"] = user
        context["user_posts"] = user_posts
        context["user_comments"]=user_comments
        context["following"]=following
        context["posts_viewed"]=posts_viewed
        return context


#################################################
## allows a user to create a bio
#################################################
class Bio(LoginRequiredMixin,generic.UpdateView):
    login_url="/accounts/login/"
    template_name="accounts/my_bio_form.html"
    form_class=forms.bioForm
    model=models.userProfile


#################################################
## allows a user the view the available cartegories
#################################################
class interestView(LoginRequiredMixin,generic.DetailView):
    login_url="/accounts/login/"
    template_name="accounts/interests_page.html"
    model=models.userProfile
    context_object_name="user_interests"

    def get_context_data(self,**kwargs):
        user_interests = models.userProfile.objects.get(user__exact=get_user_model().objects.get(username__exact=self.kwargs.get("username"))).interests.all()
        context = super(interestView,self).get_context_data(**kwargs)
        context["user_interests"]=user_interests
        return context


################################################
## allows a user to follow another user
#############################################
@login_required
def follow_view(request,**kwargs):
    userprofile=models.userProfile.objects.get(pk=kwargs.get("pk"))
    if userprofile != request.user.userprofile:
        userprofile.follower.add(request.user.userprofile)
    return HttpResponseRedirect(request.META.get('HTTP_REFERER'))


#################################################
## this views allows a user to see all the people they follow
#################################################
class Following(LoginRequiredMixin,generic.ListView):
    login_url="/accounts/login/"
    model = models.userProfile
    context_object_name = "people_you_follow"
    template_name = "accounts/following.html"

    def get_queryset(self,**kwargs):
        userprofiles = models.userProfile.objects.all()
        user = userprofiles.get(user = get_user_model().objects.get(username=self.kwargs.get("username")))
        people_you_follow = userprofiles.filter(follower=user)
        return people_you_follow


###################################################
## allows a user to unfollow another user
###################################################
@login_required
def unfollow_view(request,**kwargs):
    userprofile=models.userProfile.objects.get(pk=kwargs.get("pk"))
    if userprofile != request.user.userprofile:
        userprofile.follower.remove(request.user.userprofile)
    return HttpResponseRedirect(request.META.get('HTTP_REFERER'))


###########################################################
## allows a user to change their profile/background pic
###########################################################


@login_required
def change_profile_pic_view(request,**kwargs):

    if request.method == 'POST':
        user = models.userProfile.objects.get(user__exact=get_user_model().objects.get(username=kwargs.get("username")))
        data = request.POST.copy()
        profile_pic_url = data.get("profile_pic_url")
        background_pic_url = data.get("background_pic_url")
        print(profile_pic_url)
        print(background_pic_url)

        if (profile_pic_url != "" and profile_pic_url != None):
            user.profile_pic = "https://res.cloudinary.com/raymondndibe/"+profile_pic_url

        if (background_pic_url != "" and background_pic_url != None):
            user.background_pic = "https://res.cloudinary.com/raymondndibe/"+background_pic_url

        user.save()


        return HttpResponseRedirect(reverse_lazy("accounts:user_profile",kwargs={"username":kwargs.get("username"),"pk":kwargs.get("pk")}))

    else:

        return render(request,'accounts/change_profile_pic_form.html')




#############################################################
## allows a user to sign up to the platform
#############################################################
def signup(request):

    signedup = False

    if request.method == 'POST':
        print(request.POST["gender"])##########The solution
        # Get info from "both" forms
        # It appears as one form to the user on the .html page
        signup_form = forms.signupForm(data=request.POST)
        gender_form = forms.userGenderForm(data=request.POST)
        # Check to see both forms are valid
        if signup_form.is_valid() and gender_form.is_valid():

            # Save User Form to Database
            user = signup_form.save()

            # Hash the password
            user.set_password(user.password)

            # Update with Hashed password
            user.save()
            user_gender=gender_form.save(commit=False)
            user_gender.user = user
            user_gender.save()
            # Registration Successful!
            signedup = True
            return HttpResponseRedirect(reverse_lazy("login"))

        else:
            # One of the forms was invalid if this else gets called.
            print(signup_form.errors)

    else:
        # Was not an HTTP post so we just render the forms as blank.
        signup_form = forms.signupForm()
        gender_form=forms.userGenderForm()

    return render(request,'accounts/signup.html',{'form':signup_form,'signedup':signedup,"gender_form":gender_form})




#####################################################
## allows a user to select his or her cartegory interests
#####################################################
@login_required
def selectinterest(request):

    interestselected = False
    if request.method == 'POST':
        #assigns the selected cartegories and the user instance to the interestSelectForm
        interest_select_form = forms.interestSelectForm(data=request.POST,instance=request.user)

        #checks if the interest form is valid
        if interest_select_form.is_valid():
            user=interest_select_form.save(commit=False)
            #gets the actual list of interests from the request.POST
            interests = request.POST.getlist('interests')
            #iterate through them and add all of them to the user.userprofile.interests in the userprofile model
            for each_pk in interests:
                user.userprofile.interests.add(Cartegory.objects.get(id=each_pk))
            interestselected = True
            return HttpResponseRedirect(reverse_lazy("accounts:select_pic"))
            # return redirect("accounts:select_pic")
        else:
            print(interest_select_form.errors)
    else:
        if request.user.is_active:
            user_profile_query = models.userProfile.objects.get(user__exact=request.user)
            if user_profile_query.interests.all():
                print(user_profile_query.interests,"interests already selected")
                # return HttpResponseRedirect(reverse("accounts:select_pic"))
                return redirect("accounts:select_pic")
            else:
                print(user_profile_query.interests,"no interests selected yet")
        else:
            pass
        interest_select_form = forms.interestSelectForm()
    return render(request,'accounts/choose_interests_page.html',{'form':interest_select_form,'interestselected':interestselected})
#


######################################################
## allows a user to choose a profile picture
######################################################
@login_required
def selectprofilepicture(request):
    profilepictureselected = False
    profile=request.user

    if request.method == 'POST':
        # #assigns the selected profile picture and the user instance to the profilePicSelectForm
        # profile_pic_select_form = forms.profilePicSelectForm(data=request.POST,instance=request.user)
        # #check if the selected picture is valid
        # if profile_pic_select_form.is_valid():
        #     user_pic = profile_pic_select_form.save(commit=False)
        #
        #     if 'profile_pic' in request.FILES:
        #         # If yes, then grab it from the POST form reply
        #         user_pic.userprofile.profile_pic = request.FILES['profile_pic']
        #
        #     # Now save model
        #     user_pic.userprofile.save()

write_space/accounts/templates/accounts/base.html
<!DOCTYPE html>
{%load staticfiles%}
<html lang="en" dir="ltr">
<head>
  <!-- Latest compiled and minified CSS -->
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'write_space/css/master.css' %}">

<!-- <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css"> -->


  <title></title>
</head>
  <body>
    {% block body_block %}
    {%endblock%}

    <script src="http://code.jquery.com/jquery-3.1.1.js" integrity="sha256-16cdPddA6VdVInumRGo6IbivbERE8p7CQR3HzTBuELA=" crossorigin="anonymous"></script>  <!-- Latest compiled and minified JavaScript -->
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>

    <script src="{% static 'write_space/js/transparent_to_solid_navbar.js' %}"></script>
    <script src="{% static 'write_space/js/js/back_to_top.js' %}"></script>



  </body>
</html>

write_space/accounts/templates/accounts/change_profile_pic_form.html
{% extends "header_footer.html" %}
{% load staticfiles %}
{% load cloudinary %}

{% block content %}

<div class="container change_profile_pic">
  {% include 'accounts/includes/_cloudinary_elements.html' %}
  <hr>
  <form class="user_pic_form" enctype="multipart/form-data" method="post">
      {%csrf_token%}
      <button type="submit" name="button" class="btn btn-primary">Done</button>
      <a href="{% url 'accounts:user_profile' username=request.user.username pk=request.user.pk %}">
        <input type="button" name="" value="Cancel" class="btn btn-primary"></a>
  </form>

</div>
<br>
<br>
<br>
<br>



{% endblock %}

write_space/accounts/templates/accounts/following.html
{%extends "header_footer.html" %}
{%load staticfiles%}


{%block content%}
<br>
<br>
<br>
<br>

<div class="container">
{%if people_you_follow%}
  <div class="row">
{%for each_person in people_you_follow%}

    <div class="col-lg-3 col-md-4 col-sm-6 col-xs-12 text-center">
      <div class="" style="background:white; padding:10px">
        {%if each_person.profile_pic%}
       <img src="{{each_person.profile_pic}}" class="img-responsive avatar"  alt="">
       {%endif%}
       <br>
       <a href="{%url 'accounts:user_profile' username=each_person.user.username pk=each_person.pk %}"><h5 class="name no_underline">{{each_person.user.username}}</h5></a>
       {%if not request.user.userprofile == each_person%}
       {%if not request.user.userprofile in each_person.follower.all %}
       <a href="{%url 'accounts:follow' username=each_person.user.username pk=each_person.pk %}">
       <button type="button"  class="btn btn-primary"><span class="">Follow</span>
       </button>
       </a>
       {%else%}
       <a href="{%url 'accounts:unfollow' username=each_person.user.username pk=each_person.pk %}">
       <button type="button" class="btn btn-primary"><span class="">Unfollow</span>
       </button>
       </a>
       {%endif%}
       {%endif%}

       <br>
      </div>

    </div>
    {%endfor%}
    <br>


  </div>
  {%else%}
  <div class="jumbotron text-center">
    <h3>You Are Not Following Anyone</h3>
  </div>
  {%endif%}

</div>
<br>
<br>



{%endblock%}

write_space/accounts/templates/accounts/interests_page.html
{%extends "header_footer.html" %}
{%load staticfiles%}


{%block content%}
<br>
<br>
<br>
<br>




{%if user_interests%}
<div class="row">
  <div class="">
{%for cartegory in user_interests%}
      <div class="col-lg-3 col-md-4 col-sm-6 col-xs-12 content" style="height:400px">
        {%if cartegory.image%}
         <img src="{{cartegory.image.url}}" alt="" width="100%" style="padding:0px;height:200px">
         {%endif%}
        <a href="{%url 'posts:cartegory' name=cartegory.name %}">
            <h1 class="no_underline text-center">{{cartegory.name}}</h1>
        </a>
        {%if cartegory in request.user.userprofile.interests.all %}
        <a class="btn btn-primary" href="{% url 'posts:leave_cartegory' pk=cartegory.pk%}" style="float:right">Leave</a>
        {%else%}
        <a class="btn btn-primary" href="{% url 'posts:join_cartegory' pk=cartegory.pk%}" style="float:right">Join</a>
        {%endif%}
      </div>



{%endfor%}
</div>
</div>


{%endif%}

{%endblock%}

write_space/accounts/templates/accounts/login.html
{% extends "base.html" %}
{% load staticfiles %}

{% block body_block %}
<div class="contentDiv">
  <br>
    <br>
    <div class="container">
    <a href="{% url 'landing_page' %}"><img  src="{%static 'write_space/images/close-button (4).png' %}" alt="" class="pull-right img-responsive"></a>
    </div>
    <br>
    <br>
  <div>

    <div class="container jumbotron edge" style="background-color:rgba(255,255,255,1);border-radius:10px;">
      <h1>Login</h1>
      <p><h3><a href="{% url 'accounts:signup' %}">click here</a> to signup if you don't have an account yet</h3></p>


    </div>

    <div class="container">
      <form method="post">
        {%csrf_token%}
        {%include 'includes/bs3_form.html' with form=form%}

        <button type="submit" class="btn btn-primary">Login</button>
      </form>
    </div>

  </div>
</div>
{% endblock %}

write_space/accounts/templates/accounts/user_profile.html
{%extends "header_footer.html" %}
{%load staticfiles%}

{% block content%}

{%if user.userprofile.background_pic%}
<div class=" container" id="profile_header" style="background-image: url({{user.userprofile.background_pic}});
height: 100%;background-position: center;background-repeat: no-repeat;
background-size: cover;filter:blur(8px);-webkit-filter:blur(8px)">

{%else%}
<div class="container no_background_pic" id="profile_header">
{%endif%}
</div>
<div class="profile">

  {%if request.user == user %}
  <div class="text-muted" id="upload_cover_photo">
   <a href="{%url 'accounts:change_pic' username=user.username pk=user.pk %}" class="no_underline user_profile_info" role="button">
     <span class="">+ Upload Cover Photo</span>
     <i class="fa fa-picture-o" aria-hidden="true"></i>
   </a>
  </div>
  {%endif%}
 <div class="text-center">
   {% if request.user == user %}
        <a href="{%url 'accounts:change_pic' username=user.username pk=user.pk %}"><button type="button" class="btn btn-default" style="color:black;">
          <i class="fa fa-camera"></i>
          <span class="profile__photo_upload_text">Edit</span>
        </button></a>
        {%endif%}
  <div style="margin:10px;">
  {%if user.userprofile.profile_pic%}
  <img src="{{user.userprofile.profile_pic}}" alt="" class="" id="profile_pic">
  {%else%}

  {%endif%}

  </div>
   <h2 class="user_profile_info">{{user.username}}</h2>

    <span class="user_profile_info">
      <span>{{user.userprofile.date_joined|date:"D M Y"}}</span>
    </span>

   <div>
    {%if request.user != user %}
   {%if not request.user.userprofile in user.userprofile.follower.all %}
   <br>

   <a href="{%url 'accounts:follow' username=user.username pk=user.pk %}">
    <button type="button" class="btn btn-primary"><span class="">Follow</span>
    </button>
   </a>
   <br>
   {%else%}
   <br>

   <a href="{%url 'accounts:unfollow' username=user.username pk=user.pk %}">
    <button type="button" class="btn btn-primary"><span class="">Unfollow</span>
    </button>
   </a>
   <br>
   {%endif%}
   {%endif%}
   <br>

   </div>

 </div>
</div>


<ul id="hori_list" class="text-center">

  <li>
    <a href="{%url 'posts:user_post_list' username=user.username %}" style="text-decoration:none;color:black;">
      <span class="">
        <div class="">{{user_posts.count}}</div>
        <div class="text-muted">Posts</div>
      </span>
    </a>
  </li>
  <li>
    <span class="">
      <div class="">{{posts_viewed.count}}</div>
      <div class="text-muted">Post viewed</div>
    </span>
  </li>
  <li>
    <span class="">
    <div class="">{{user_comments.count}}</div>
    <div class="text-muted">Comments</div>
  </span>
 </li>
  <li>
    <span class="">
      <div class="">{{user.userprofile.follower.count}}</div>
      <div class="text-muted">Followers</div>
    </span>
  </li>
  <li>
  	<span class="">
      <div class="">{{following.count}}</div>
      <div class="text-muted">Following</div>
    </span>
  </li>
</ul>


<nav class="navbar navbar-default" style="background-color:white;">
  <ul class="nav navbar-nav" id="profile_nav">
    <li class="">
      <a id="" href="{%url 'posts:user_post_list' username=user.username %}" class="">
        <span class="">Posts</span>
      </a>
    </li>
    <li class="">
      <a id="" href="{%url 'accounts:interests' username=user.username pk=user.userprofile.pk %}" class="">
        <span class="">interests</span>
      </a>
    </li>
    {%if request.user == user%}
    <li class="">
      <a id="" name="" href="{% url 'posts:view_saved' username=user.username %}" class="">
        <span class="">Saved</span>
      </a>
    </li>
    {%endif%}
    {%if request.user.userprofile in user.userprofile.follower.all or request.user == user %}
    <li class="">
      <a id="" name="" href="{%url 'accounts:following' username=user.username pk=user.pk %}" class="">
        <span class="">following</span>
      </a>
    </li>
    {%endif%}
  </ul>
</nav>


{%if request.user == user or user.userprofile.bio %}
<div class="container">
  <span class=""><h4>About Me</h4></span>
  {%if request.user == user %}
  <a href="{%url 'accounts:bio' username=user.username pk=user.userprofile.pk %}"><button type="button" class="btn btn-default" style="float: right;">
    <i class="fa fa-pencil" style="font-size: 16px;"></i> Edit Bio</button></a>
  {%endif%}
    <div class="jumbotron text-center">
      {% if not user.userprofile.bio %}
      Tell peopled a little about yourself. Interests, hobbies, and current projects can all go here.
      {%else%}
      <h4>{{user.userprofile.bio}}</h4>
      {%endif%}
    </div>
</div>
<hr>
{%endif%}


{%if request.user == user or user_posts %}
<div class="" style="padding-right:15px; padding-left: 15px">
  <div class="">
    <span class=""><h4>Top Posts</h4></span>
    <a href="{%url 'posts:user_post_list' username=user.username %}">
      <span class="">SEE ALL ></span>
    </a>
{%if request.user == user %}
    <a href="{%url 'posts:create_post' username=request.user.username %}"><button type="button" style="float: right;" class="btn btn-success btn-lg">Create Post</button></a>
{%endif%}


  </div>
  <br>
  <br>
  <div class=" jumbotron text-center">
{%if not user_posts%}
    <div class="" style="font-weight:bolder;">
      You haven't posted anything yet.
    </div>
{%endif%}
  </div>
</div>
{%else%}
<div class="container">
<br>
<br>
<div class=" jumbotron text-center">
  <div class="">
    <div class="" style="font-weight:bolder;">
      This user haven't written any posts yet.
    </div>
    check back again later
  </div>
</div>
</div>
<hr>
{%endif%}


<div class="interests container">
  <div class="">
    <span class=""><h4>Interests</h4></span>
  </div>

  <table>
    {%for cartegory in user.userprofile.interests.all %}
    <tr>
      <a href="{%url 'posts:cartegory' name=cartegory.name %}" class="" style="text-decoration:none;">
      <span class="">
        <i class="fa fa-tech"></i>
      <span class="">{{cartegory.name}}</span>
      </span>
     </a>
    </tr>
    {%endfor%}
  </table>
</div>
<hr>


<!-- <div class="container-fluid">
 <div class="jumbotron text-center">
 <div class="">
    <h4>Saved</h4>
  </div>
  <br>
  <div class="">
	  <div class="" style="font-weight:bolder;">
	    You don’t have any drops saved.
	  </div>
	  Save your favorite drops to let people know what you’re interested in, or use this section as a wish list!
 </div>
 </div>
</div>
<hr>


<div class="container-fluid">
 <div class="jumbotron text-center">
  <div class="profile__about_section_title">
    <h4>Following: 0</h4>
  </div>
  <br>

  <div class="">
    <div class="" style="font-weight:bolder;">
      You aren't following anyone yet.
    </div>
    Follow people to get updates when they publish something new.
  </div>
 </div>
</div>
<hr>

<div class="container-fluid">
 <div class="jumbotron text-center">
  <div class="">
    <h4>Followers: 0</h4>
  </div>
  <br>
  <div class="">
    <div class="" style="font-weight:bolder;">
      No one's following you yet.
    </div>
    Your followers will get updates when you publish something new.
  </div>
 </div>
</div>
<br>
<br> -->





{%endblock%}