write_space/accounts/urls.py
from django.contrib.auth import views as auth_views
from django.urls import path
from . import views
from accounts.forms import LoginForm

app_name="accounts"

urlpatterns=[
path("login/",auth_views.LoginView.as_view(authentication_form=LoginForm,template_name="accounts/login.html"),name="login"),
path("logout/",auth_views.LogoutView.as_view(),name="logout"),
path("signup/",views.signup,name="signup"),
path("first_step/",views.selectinterest,name="select_interest"),
path("second_step/",views.selectprofilepicture,name="select_pic"),
path("user_profile/<str:username>/<int:pk>/",views.profileView.as_view(),name="user_profile"),
path("user_profile/change_pic/<str:username>/<int:pk>/",views.change_profile_pic_view,name="change_pic"),
path("follow/<str:username>/<int:pk>/",views.follow_view,name="follow"),
path("unfollow/<str:username>/<int:pk>/",views.unfollow_view,name="unfollow"),
path("<str:username>/<int:pk>/following",views.Following.as_view(),name="following"),
path("<str:username>/<int:pk>/Bio",views.Bio.as_view(),name="bio"),
path("interests/<str:username>/<int:pk>/",views.interestView.as_view(),name="interests"),
]

write_space/posts/api/urls.py
from django.urls import path
from . import views

app_name = "posts_api"

urlpatterns = [

 # path("<str:username>/post/all/",views.userPostListView.as_view(),name="user_post_list"),
 # path('<str:username>/post/<int:pk>/',views.userPostDetailView.as_view(),name="user_post_detail"),
 # path("<int:pk>/unsave/",views.postUnsaveView.as_view(),name="unsave"),
 # path('<int:pk>/save_for_future/',views.postSaveView.as_view(),name="save_for_future"),
 path("all/",views.postListApiView.as_view(),name="post_list"),
 path('<int:pk>/',views.postDetailApiView.as_view(),name="post_detail"),
 path("<str:username>/new/",views.postCreateApiView.as_view(),name="create_post"),
 path('<int:pk>/edit/',views.postUpdateApiView.as_view(),name="edit_post"),
 path('<str:username>/<int:pk>/delete/',views.postDeleteApiView.as_view(),name="delete_post"),
 path('<int:pk>/comments/',views.commentsApiView.as_view(),name="comments"),
 path('<int:pk>/comments/add/',views.addCommentApiView.as_view(),name="add_comment"),
 path('comments/<int:pk>/edit/',views.editCommentApiView.as_view(),name="edit_comment"),
 # path("<str:username>/saved/",views.savedListView.as_view(),name="view_saved"),
 # path('<int:pk>/comment/',views.add_comment_to_post,name="add_comment_to_post"),
 # path('<int:pk>/clap/',views.postClapView.as_view(),name="clap"),
 # path('cartegory/<str:name>/',views.cartegoryView.as_view(),name="cartegory"),
 # path('<int:pk>/publish/',views.post_publish,name="post_publish"),
 # path('<int:pk>/unpublish/',views.post_unpublish,name="post_unpublish"),
 # path('join_cartegory/<int:pk>/',views.join_cartegory_view,name="join_cartegory"),
 # path('leave_cartegory/<int:pk>/',views.leave_cartegory_view,name="leave_cartegory"),

]

write_space/posts/urls.py
from django.urls import path
from . import views
from .feeds import LatestPostsFeed

app_name = "posts"

urlpatterns = [

 path("<str:username>/post/all/",views.userPostListView.as_view(),name="user_post_list"),
 path('<str:username>/post/<int:pk>/',views.userPostDetailView.as_view(),name="user_post_detail"),
 path("<int:pk>/unsave/",views.postUnsaveView.as_view(),name="unsave"),
 path('<int:pk>/save_for_future/',views.postSaveView.as_view(),name="save_for_future"),
 path("all/",views.postListView.as_view(),name="post_list"),
 path('<int:pk>/',views.PostDetailView.as_view(),name="post_detail"),
 path("<str:username>/new/",views.CreatePostView.as_view(),name="create_post"),
 path('<int:pk>/edit/',views.PostUpdateView.as_view(),name="edit_post"),
 path('<str:username>/<int:pk>/delete/',views.PostDeleteView.as_view(),name="delete_post"),
 path("<str:username>/saved/",views.savedListView.as_view(),name="view_saved"),
 path('<int:pk>/comment/',views.add_comment_to_post,name="add_comment_to_post"),
 path('<int:pk>/clap/',views.postClapView.as_view(),name="clap"),
 path('<int:pk>/un_clap/',views.postUnClapView.as_view(),name="un_clap"),
 path('cartegory/<str:name>/',views.cartegoryView.as_view(),name="cartegory"),
 path('<int:pk>/publish/',views.post_publish,name="post_publish"),
 path('<int:pk>/unpublish/',views.post_unpublish,name="post_unpublish"),
 path('join_cartegory/<int:pk>/',views.join_cartegory_view,name="join_cartegory"),
 path('leave_cartegory/<int:pk>/',views.leave_cartegory_view,name="leave_cartegory"),
 path("feed/rss", LatestPostsFeed(), name="post_feed"),
]

write_space/write_space/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static
from rest_framework_jwt.views import obtain_jwt_token,refresh_jwt_token
from . import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path("", views.LandingPage.as_view(),name="landing_page"),
    path("posts/",include("posts.urls",namespace="posts")),
    path("api/posts/",include("posts.api.urls",namespace="posts_api")),
    path("accounts/",include("accounts.urls",namespace="accounts")),
    path("api/token-auth/", obtain_jwt_token),
    path("api/refresh_token/",refresh_jwt_token),
    path("api/accounts/",include("accounts.api.urls",namespace="accounts_api")),
    path("api/images/<int:pk>/<str:username>/<str:folder>/<str:public_id>/<str:type>/delete",
    views.delete_image_async,name="delete_image_async"),
    path("accounts/",include("django.contrib.auth.urls")),
    path("about_me/",views.aboutView.as_view(),name="about_me"),
    path('summernote/', include('django_summernote.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

write_space/posts/models.py
from django.db import models
from django.contrib.auth import get_user_model
from mptt.models import MPTTModel,TreeForeignKey
from django.urls import reverse
from django.utils import timezone
from django.utils.text import slugify
import cloudinary
import os

# Create your models here.
User = get_user_model()

class Post(models.Model):
    author= models.ForeignKey(User,on_delete = models.CASCADE,related_name="authors")
    title = models.CharField(max_length = 255,unique = True)
    main_image = models.TextField(blank=True,null=True)
    cartegory = TreeForeignKey('Cartegory',null=True,blank=True,on_delete = models.CASCADE,related_name="cartegories")
    clap = models.ManyToManyField(User,blank=True,related_name="claps")
    viewed = models.ManyToManyField(User,blank=True,related_name="viewed")
    post_heading = models.CharField(max_length = 120)
    text = models.TextField(blank = True, default = "")

    created_at = models.DateTimeField(auto_now=True)
    slug = models.SlugField()
    publish_date=models.DateTimeField(blank=True , null=True,default=None)

    def save(self,*args,**kwargs):
        print("save was called")
        print("the text",self.text)
        text = ""
        try:
            text = self.text.split("src=\"")[1].split("\"")[0]
        except:
            pass

        if text == "":
            pass
        else:
            self.main_image = text
            print("self.main_image was set",text)

        if self.slug:
            pass
        else:
            self.slug = slugify(self.title)
            print("self.slug was set",self.slug)

        super().save(*args,**kwargs)


    def publish(self):
        self.publish_date=timezone.now()
        self.save()

    def unpublish(self):
        self.publish_date=None
        self.save()


    def get_absolute_url(self):
        return reverse("posts:user_post_list",kwargs={"username":self.author})

    def __str__(self):
        return self.title

    class Meta:
        ordering=["-created_at"]
        unique_together=["title","text"]



class Cartegory(MPTTModel):
    name = models.CharField(max_length=50, unique=True)
    image = models.URLField(null=True,blank=True)
    parent = TreeForeignKey('self', null=True, blank=True, related_name='children',db_index=True,on_delete = models.CASCADE)
    slug = models.SlugField()

    def __str__(self):
        return self.name

    class MPTTMeta:
        order_insertion_by = ['name']

    class Meta:
        unique_together = (('parent', 'slug',))
        verbose_name_plural = 'cartegories'

    def get_slug_list(self):
        try:
            ancestors = self.get_ancestors(include_self=True)
        except:
            ancestors = []
        else:
            ancestors = [ i.slug for i in ancestors]
        slugs = []
        for i in range(len(ancestors)):
            slugs.append('/'.join(ancestors[:i+1]))
        return slugs





class Comment(models.Model):
    post=models.ForeignKey(Post,on_delete=models.CASCADE ,related_name="comments")
    author=models.ForeignKey(User,on_delete=models.CASCADE)
    text=models.TextField(blank = True, default = "")
    created_at=models.DateTimeField(auto_now=True)

    def get_absolute_url(self):
        return reverse("post_details",kwargs={"pk":self.pk})

    def __str__(self):
        return self.text

write_space/posts/forms.py
from django import forms
from posts.models import Post, Comment
from django_summernote.widgets import SummernoteWidget, SummernoteInplaceWidget

class PostForm(forms.ModelForm):

    class Meta():
        # main_image=forms.HiddenInput()
        model=Post
        fields=("title","post_heading","text","cartegory")
        widgets={
        "title":forms.TextInput(attrs={"class":"form-control","placeholder":"title of your post"}),
        "post_heading":forms.TextInput(attrs={"class":"form-control","placeholder":"provide any suitable heading for your post"}),
        'text': SummernoteWidget()
        }

# "text":forms.Textarea(attrs={"class":"form-control","placeholder":"Create your post here"}),

class imageForm(forms.ModelForm):
    class Meta():
        model=Post
        fields = ("main_image",)

class CommentForm(forms.ModelForm):

    class Meta():
        model=Comment
        fields=("text",)

        widgets={
        "text":forms.Textarea(attrs={"class":"form-control"}),
        }

write_space/posts/api/views.py
from rest_framework.generics import (ListAPIView,RetrieveAPIView
,RetrieveUpdateAPIView,RetrieveDestroyAPIView,CreateAPIView)

from rest_framework.permissions import (AllowAny,IsAuthenticated,IsAdminUser
,IsAuthenticatedOrReadOnly)
from rest_framework.filters import SearchFilter,OrderingFilter
from rest_framework.mixins import DestroyModelMixin, UpdateModelMixin
from posts.api.permissions import IsOwnerOrReadOnly

from posts.models import Post,Comment
from posts.api import serializers

from .pagination import postLimitOffsetPagination,postPageNumberPagination

class postListApiView(ListAPIView):
    queryset = Post.objects.all()
    serializer_class = serializers.postListSerializer
    permission_classes = [AllowAny]
    filter_backends = [SearchFilter,OrderingFilter]
    search_fields = ["title","text","author__username","publish_date","post_heading"]
    pagination_class = postPageNumberPagination#postLimitOffsetPagination


class postDetailApiView(RetrieveAPIView):
    queryset = Post.objects.all()
    serializer_class = serializers.postDetailSerializer
    permission_classes = [AllowAny]

class postUpdateApiView(RetrieveUpdateAPIView):
    queryset = Post.objects.all()
    serializer_class = serializers.postDetailSerializer
    permission_classes = [IsAuthenticatedOrReadOnly,IsOwnerOrReadOnly]

    def perform_update(self,serializer):
        serializer.save(author=self.request.user)

class postDeleteApiView(RetrieveDestroyAPIView):
    queryset = Post.objects.all()
    serializer_class = serializers.postDetailSerializer
    permission_classes = [IsAuthenticatedOrReadOnly,IsOwnerOrReadOnly]


class postCreateApiView(CreateAPIView):
    queryset = Post.objects.all()
    serializer_class = serializers.postCreateSerializer
    permission_classes = [IsAuthenticated,IsAdminUser]

    def perform_create(self,serializer):
        serializer.save(author=self.request.user)

class commentsApiView(ListAPIView):
    serializer_class = serializers.postCommentsSerializer
    permission_classes = [AllowAny]

    def get_queryset(self,*args,**kwargs):
        return Comment.objects.filter(post__pk=self.kwargs.get("pk"))

class addCommentApiView(CreateAPIView):
    serializer_class = serializers.addCommentSerializer

    def perform_create(self,serializer,*args,**kwargs):
        serializer.save(author=self.request.user,post=Post.objects.get(pk=self.kwargs.get("pk")))

class editCommentApiView(DestroyModelMixin,UpdateModelMixin,RetrieveAPIView):
    queryset = Comment.objects.all()
    serializer_class = serializers.editCommentSerializer
    permission_classes = [IsAuthenticated,IsOwnerOrReadOnly]

    def put(self,request,*args,**kwargs):
        return self.update(request,*args,**kwargs)

    def delete(self,request,*args,**kwargs):
        return self.destroy(request,*args,**kwargs)

write_space/posts/templates/posts/post_detail.html
{%extends "header_footer.html" %}
{%load staticfiles%}
{%block content%}
<div class="post-detail">

	<div class="content">
				{% if post.publish_date%}
					<div class="post-detail-header">
						<h1 class="post-title">{{post.title}}</h1>
						<h2 class="text-muted banner_post_content__body">{{post.post_heading|safe|linebreaksbr}}</h2>

						<div class="author">
						<div class="author-details">

						{%if post.author.userprofile.profile_pic%}
					 <img src="{{post.author.userprofile.profile_pic}}" class="img-responsive avatar" alt="">
					 {%endif%}
					 <div style="padding-left:0.5em;padding-right:0.5em">
						 <a class="banner_post_content__creator__a name" href="{%url 'accounts:user_profile' pk=post.author.pk username=post.author.username %}">
				       {{post.author}}
						 </a>

						 {%if request.user != post.author %}
						 {%if not request.user.userprofile in post.author.userprofile.follower.all %}
						 <a href="{%url 'accounts:follow' username=post.author.username pk=post.author.pk %}">
						 <button type="button" class="btn btn-primary"><span class="">Follow</span>
						 </button>
						 </a>
						 {%else%}
						 <a  href="{%url 'accounts:unfollow' username=post.author.username pk=post.author.pk %}">
						 <button type="button" class="btn btn-primary"><span class="">Unfollow</span>
						 </button>
						 </a>
						 {%endif%}
						 {%endif%}

					<p>{{post.publish_date|date:"d M, Y"}}</p>
					  </div>
					 </div>

					 <div class="social">

          <i class="black fa fa-share-alt" style="display:inline-block;margin:0 1.2em 0 1.2em" data-toggle="modal" data-target="#social-share" aria-hidden="true"></i>

					 <!-- Modal -->
				<div class="modal fade" id="social-share" tabindex="-1" role="dialog" aria-labelledby="share post" aria-hidden="true">
				  <div class="modal-dialog modal-dialog-centered" role="document">
				    <div class="modal-content">
				      <div class="modal-header">
				        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
				          <span aria-hidden="true">&times;</span>
				        </button>
				      </div>
				      <div class="modal-body" style="display:flex;flex-wrap:wrap;justify-content:space-between">
								<button class="btn btn-light" data-sharer="twitter" data-url={{request.build_absolute_uri}} data-title="{{post.title}}">
									<i class="black fa fa-twitter fa-lg" aria-hidden="true"></i>
								</button>

								<button class="btn btn-light" data-sharer="facebook" data-url={{request.build_absolute_uri}} data-title="{{post.title}}">
									<i class="black fa fa-facebook fa-lg" aria-hidden="true"></i>
								</button>

								<button class="btn btn-light" data-sharer="linkedin" data-url={{request.build_absolute_uri}} data-title="{{post.title}}">
									<i class="black fa fa-linkedin fa-lg" aria-hidden="true"></i>
								</button>

								<button class="btn btn-light" data-sharer="email" data-url={{request.build_absolute_uri}} data-title="{{post.title}}">
									<i class="black fa fa-envelope fa-lg" aria-hidden="true"></i>
								</button>

								<button class="btn btn-light" data-sharer="whatsapp" data-web="true" data-url={{request.build_absolute_uri}} data-title="{{post.title}}">
									<i class="black fa fa-whatsapp fa-lg" aria-hidden="true"></i>
								</button>

								<button class="btn btn-light" data-sharer="telegram" data-url={{request.build_absolute_uri}} data-title="{{post.title}}">
									<i class="black fa fa-telegram fa-lg" aria-hidden="true"></i>
								</button>

								<button class="btn btn-light" data-sharer="hackernews" data-url={{request.build_absolute_uri}} data-title="{{post.title}}">
									<i class="black fa fa-y-combinator fa-lg" aria-hidden="true"></i>
								</button>

								<button class="btn btn-light" data-sharer="reddit" data-url={{request.build_absolute_uri}} data-title="{{post.title}}">
									<i class="black fa fa-reddit-alien fa-lg" aria-hidden="true"></i>
								</button>

				      </div>
				    </div>
				  </div>
				</div>

					 {%if post.author != request.user %}
					 {%if not post in request.user.userprofile.saved_for_future.all %}
					 <a href="{%url 'posts:save_for_future' pk=post.pk %}"><i class="black fa fa-bookmark-o fa-lg" aria-hidden="true"></i></a>
					 {%else%}
					 <a href="{%url 'posts:unsave' pk=post.pk %}"><i class="black fa fa-bookmark fa-lg" aria-hidden="true"></i></a>
					 {%endif%}
					 {%endif%}
					 </div>
					 </div>

					 </div>

					<div class="post-detail-text" id="post_text">
						{{post.text|safe|linebreaksbr}}
						<hr>
					</div>
					<div class="date post-date">
						<span><i class="black fa fa-eye fa-lg" style="display:inline-block;margin:0 0.5em 0 0" aria-hidden="true"></i>
							 {{post.viewed.count}}</span>
						{%if post.author == request.user %}
						<span><i class="black fa fa-thumbs-up fa-lg" style="display:inline-block;margin:0 0.5em 0 1.2em" aria-hidden="true"></i>{{post.clap.count}}</span>
						{%else%}
						{%if not request.user in post.clap.all %}
						<a class="black" href="{%url 'posts:clap' pk=post.pk %}">
								<span><i class="black fa fa-thumbs-o-up fa-lg" style="display:inline-block;margin:0 0.5em 0 1.2em" aria-hidden="true"></i>{{post.clap.count}}</span>
						</a>
						{%else%}
						<a class="black" href="{%url 'posts:un_clap' pk=post.pk %}">
								<span><i class="black fa fa-thumbs-up fa-lg" style="display:inline-block;margin:0 0.5em 0 1.2em" aria-hidden="true"></i>{{post.clap.count}}</span>
						</a>
						{%endif%}
						{%endif%}

						{%if post.author == request.user%}
						<a class="btn btn-default" href="{% url 'posts:post_unpublish' pk=post.pk%}">Unpublish</a>
						<a class="btn btn-primary" href="{% url 'posts:edit_post' pk=post.pk %}"><span class="glyphicon glyphicon-pencil"></span></a>
						<a class="btn btn-primary" href="{% url 'posts:delete_post' username=post.author.username pk=post.pk %}"><span class="glyphicon glyphicon-remove"></span></a>
						{%endif%}
					</div>
		</div>
			 <br>
			 <br>

			 <div class="flex_featured_post_container">
				 <div style="width:100%">
					<h3 class="text-center">Recommended Read</h3>
				</div>

						{%if rec_history%}
					<div class="flex_featured_post--1 post" id="featured1">
					 {%if rec_history.main_image%}
					 <div class=" banner_post_image" >
					 <img src="{{rec_history.main_image}}" class="img-responsive" alt="" id="featured_img1">
				 </div>
				 {%endif%}
				 <div class=" banner_post_content">
					 <div>
						 <h2 class="banner_post_content__title"><a class="banner_post_content__title__a" href="{% url 'posts:post_detail' pk=rec_history.pk %}">{{rec_history.title}}</a></h2>
					 </div>
					 <div>
						 <h4 class="text-muted banner_post_content__body">{{rec_history.post_heading|truncatechars:64}}</h4>
					 </div>
					 <div>
						 <h5 class="banner_post_content__creator"><a class="banner_post_content__creator__a" href="{%url 'accounts:user_profile' pk=rec_history.author.pk username=rec_history.author.username %}">{{rec_history.author}}</a> in {{rec_history.cartegory}}</h5>
						 <p>{{rec_history.publish_date|date:"d M, Y"}}
							 <i class="fa fa-circle fa-xs" style="font-size:10px;display:inline-block;margin:0 1.2em 0 1.2em" aria-hidden="true"></i>
               <i class="fa fa-comments-o fa-lg" aria-hidden="true">&nbsp; {{rec_history.clap.all.count}}</i>
               <i class="fa fa-circle fa-xs" style="font-size:10px;display:inline-block;margin:0 1.2em 0 1.2em" aria-hidden="true"></i>
               <i class="fa fa-comments-o fa-lg" aria-hidden="true">&nbsp; {{rec_history.comments.all.count}}</i>
						 </p>
					 </div>
				 </div>
				 </div>
				 {%endif%}

				 {%if rec_follow%}
				 <div class="flex_featured_post--1 post" id="featured1">
					 {%if rec_follow.main_image%}
					 <div class=" banner_post_image" >
					 <img src="{{rec_follow.main_image}}" class="img-responsive" alt="" id="featured_img1">
				 </div>
				 {%endif%}
				 <div class=" banner_post_content">
					 <div>
						 <h2 class="banner_post_content__title"><a class="banner_post_content__title__a" href="{% url 'posts:post_detail' pk=rec_follow.pk %}">{{rec_follow.title}}</a></h2>
					 </div>
					 <div>
						 <h4 class="text-muted banner_post_content__body">{{rec_follow.post_heading|truncatechars:64}}</h4>
					 </div>
					 <div>
						 <h5 class="banner_post_content__creator"><a class="banner_post_content__creator__a" href="{%url 'accounts:user_profile' pk=rec_follow.author.pk username=rec_follow.author.username %}">{{rec_follow.author}}</a> in {{rec_follow.cartegory}}</h5>
						 <p>{{rec_follow.publish_date|date:"d M, Y"}}
							 <i class="fa fa-circle fa-xs" style="font-size:10px;display:inline-block;margin:0 1.2em 0 1.2em" aria-hidden="true"></i>
               <i class="fa fa-comments-o fa-lg" aria-hidden="true">&nbsp; {{rec_follow.clap.all.count}}</i>
               <i class="fa fa-circle fa-xs" style="font-size:10px;display:inline-block;margin:0 1.2em 0 1.2em" aria-hidden="true"></i>
               <i class="fa fa-comments-o fa-lg" aria-hidden="true">&nbsp; {{rec_follow.comments.all.count}}</i>
						 </p>
					 </div>
				 </div>
				 </div>
				 {%endif%}

				 {%if rec_interest%}
				 <div class="flex_featured_post--1 post" id="featured1">
					 {%if rec_interest.main_image%}
					 <div class=" banner_post_image" >
					 <img src="{{rec_interest.main_image}}" class="img-responsive" alt="" id="featured_img1">
				 </div>
				 {%endif%}
				 <div class=" banner_post_content">
					 <div>
						 <h2 class="banner_post_content__title"><a class="banner_post_content__title__a" href="{% url 'posts:post_detail' pk=rec_interest.pk %}">{{rec_interest.title}}</a></h2>
					 </div>
					 <div>
						 <h4 class="text-muted banner_post_content__body">{{rec_interest.post_heading|truncatechars:64}}</h4>
					 </div>
					 <div>
						 <h5 class="banner_post_content__creator"><a class="banner_post_content__creator__a" href="{%url 'accounts:user_profile' pk=rec_interest.author.pk username=rec_interest.author.username %}">{{rec_interest.author}}</a> in {{rec_interest.cartegory}}</h5>
						 <p>{{rec_interest.publish_date|date:"d M, Y"}}
							 <i class="fa fa-circle fa-xs" style="font-size:10px;display:inline-block;margin:0 1.2em 0 1.2em" aria-hidden="true"></i>
               <i class="fa fa-comments-o fa-lg" aria-hidden="true">&nbsp; {{rec_interest.clap.all.count}}</i>
               <i class="fa fa-circle fa-xs" style="font-size:10px;display:inline-block;margin:0 1.2em 0 1.2em" aria-hidden="true"></i>
               <i class="fa fa-comments-o fa-lg" aria-hidden="true">&nbsp; {{rec_interest.comments.all.count}}</i>
						 </p>
					 </div>
				 </div>
				 </div>
				 {%endif%}
			 </div>

		 <br>
		 <br>

		 <br>

		 <div class="comments">
       <h2>Comments</h2>
         <div class="comment-collapsed comment-form">

					 {% if request.user.is_authenticated %}
					 <div class="comment_meta">
					 {%if request.user.userprofile.profile_pic%}
					 <img src="{{request.user.userprofile.profile_pic}}"  class="avatar" alt="">
						{%endif%}
					<div>
					<a class="black comment_meta__a display-none" href="{%url 'accounts:user_profile' pk=request.user.userprofile.pk username=request.user.username %}">{{request.user.username}}</a>
					</div>
					</div>
					{% endif %}
					  {% include 'posts/includes/_comment_form.html' %}
					</div>

				 {% for comment in post.comments.all %}

					 <div class="comment">
						 <div class="comment_meta">
						 {%if comment.author.userprofile.profile_pic%}
						 <img src="{{comment.author.userprofile.profile_pic}}"  class="avatar" alt="">
              {%endif%}
						<div>
						<a class="black comment_meta__a" href="{%url 'accounts:user_profile' pk=comment.author.pk username=comment.author.username %}">{{comment.author}}</a>
						<p class="text-muted">{{comment.created_at}}</p>
						</div>
						</div>
						<p>{{comment.text|safe|linebreaks}}</p>
					 </div>
					 {% endfor %}
					 </div>
			 {% endif %}


</div>
<br>
<br>
<br>

{%endblock%}

write_space/posts/templates/posts/view_saved.html
{%extends "header_footer.html"%}
{%load staticfiles%}

{%block content%}
<br>
<br>
<br>
<br>
{%if saved_posts%}


<div class="container">
  <div class="flex_post_container">

    {% for post in saved_posts %}

    <div class="post flex_post" id="all">
    {%if post.main_image%}
    <div class="banner_post_image" >
    <img src={{post.main_image}} alt="" class="img-responsive" id="all_img">
    </div>
    {%endif%}
    <div class="all_post_content">
    <div>
      <h2 class="all_post_content__title"><a class="all_post_content__title__a" href="{% url 'posts:post_detail' pk=post.pk %}">{{post.title}}</a></h2>
    </div>
    <div>
      <h4 class="text-muted all_post_content__body">{{post.post_heading|truncatechars:40}}</h4>
    </div>
    <div>
      <h5 class="all_post_content_creator"><a class="all_post_content__creator__a" href="{%url 'accounts:user_profile' pk=post.author.pk username=post.author.username %}">{{post.author}}</a> in {{post.cartegory}}</h5>
      <p>{{post.publish_date|date:"d M, Y"}}
        <i class="fa fa-circle fa-xs" style="font-size:6px;display:inline-block;margin:0 1em 0 1em" aria-hidden="true"></i>
        <i class="black fa fa-thumbs-o-up" aria-hidden="true">&nbsp; {{post.clap.all.count}}</i>
        <i class="fa fa-circle fa-xs" style="font-size:6px;display:inline-block;margin:0 1em 0 1em" aria-hidden="true"></i>
        <i class="fa fa-comments-o" aria-hidden="true">&nbsp; {{post.comments.all.count}}</i></p>
    </div>
    </div>
    </div>
    {%endfor%}

  </div>
</div>

{%else%}
{% include 'posts/includes/_no_posts.html' %}
{%endif%}

{%endblock%}